### ISSUE TITLE
Tests with a . in the name are skipped when debugging

### ISSUE THREAD

**Issue by binkiesjoris** [jest-community/vscode-jest#925]
### Environment

1. `node -v`: v14.17.1
2. `npm -v` or `yarn --version`: 8.5.3
3. `npm ls jest` or `npm ls react-scripts` (if you haven’t ejected): 
├─┬ jest-mock-extended@3.0.1
│ └── jest@29.0.3 deduped
├── jest@29.0.3
└─┬ ts-jest@29.0.1
  └── jest@29.0.3 deduped
4. your vscode-jest settings if customized:
```
{
    "type": "node",
    "name": "vscode-jest-tests",
    "request": "launch",
    "console": "integratedTerminal",
    "internalConsoleOptions": "neverOpen",
    "cwd": "${workspaceFolder}",
    "runtimeExecutable": "npm",
    "args": [
        "run",
        "test",
        "--",
        "--runInBand",
        "--watchAll=false",
        "--testTimeout=999999"
    ]
}
```
5. Operating system: windows 10

### Prerequisite
- are you able to run jest test from the command line? 
  - No
- how do you run your tests from the command line?
  -  `npm run test`

### Steps to Reproduce

```
describe("something", () => {
    it("something with . in name", () => {
        expect(true).toBe(true);
    });
});
```
Create a test like above
Add a breakpoint to it
Debug the test

### Relevant Debug Info

```
PS C:\XXX>  C:; cd 'C:\XXX'; ${env:CI}='vscode-jest-tests'; ${env:NODE_OPTIONS}='--require "c:/Programs/Microsoft VS Code/resources/app/extensions/ms-vscode.js-debug/src/bootloader.bundle.js" --inspect-publish-uid=http'; 
${env:VSCODE_INSPECTOR_OPTIONS}='{"inspectorIpc":"\\\\.\\pipe\\node-cdp.16944-10.sock","deferredMode":false,"waitForDebugger":"","execPath":"C:\\Programs\\nodejs\\node.exe","onlyEntrypoint":false,"autoAttachMode":"always","fileCallback":"C:\\Users\\XXX\\AppData\\Local\\Temp\\node-debug-callback-967039d2b486d69f"}'; & 'C:\Programs\nodejs\npm.cmd' 'run' 'test' '--' '--runInBand' '--watchAll=false' '--testTimeout=999999' '--coverage=false' '--no-cache' '--testNamDebugger attached.
> XXX test
-simpleTest.test.ts"

Debugger attached.
Test Suites: 1 skipped, 0 of 1 total
Tests:       1 skipped, 1 total
Snapshots:   0 total
Time:        23.546 s
Waiting for the debugger to disconnect...
Waiting for the debugger to disconnect...
```

### Expected Behavior

Test will run and attach to debugger

### Actual Behavior

The test is skipped

**Comment by connectdotz** [comment]
I am not able to reproduce your use case... wondering if this is related to the" npm not passing through arguments" issue, which is fixed with npm >= 8.15. If you can upgrade your npm version and try again.

On the other hand, can you run this specific test outside the debugger(using the run gutter menu)? If so, what is your `jest.jestCommandLine` setting?

**Comment by binkiesjoris** [comment]
I have updated my npm version, this seems to have fixed the issue! At first it was still not hitting my breakpoint in the test, but after clearing all breakpoints and using the run debug command it now seems to be working fine.
